### ISSUE TITLE
TEST 环境下 mri open 提示 404 错误

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/lt-miniapp#152]
![image](https://user-images.githubusercontent.com/322486/31305324-ad155bb6-ab69-11e7-80e2-5ce315fcb944.png)

@fushang318 是否脚本故障？

**Comment by fushang318** [comment]
@ben7th redis 库数据突然没了，好奇怪，我先把数据重新写入了

**Comment by ben7th** [comment]
@fushang318 好的，现在正常了
