### ISSUE TITLE
会话脚本里 git 图片参数设置有误导致背景不透明

### ISSUE THREAD

**Issue by ben7th** [sibbay-ai/lt-miniapp#170]
![image](https://user-images.githubusercontent.com/322486/31422648-d7fb4ac8-ae81-11e7-91d4-db0518d47753.png)

上图中的 gif 表情，期望效果是背景透明

![image](https://user-images.githubusercontent.com/322486/31422694-10c12d28-ae82-11e7-9465-925e975d865f.png)

背景透明前端已作处理，但目前脚本数据中 data.show 对应内容中 type 为 img, 需要把 type 改成 gif 才有透明效果

@georgeliuyu 此类问题我以后是固定 AT @fushang318 吗？

**Comment by fushang318** [comment]
@ben7th 我来修复

**Comment by fushang318** [comment]
@ben7th  测试环境已经改为 git ，但是发现如下问题，图片载入不了
![image](https://user-images.githubusercontent.com/326242/31424210-a1c50876-ae1e-11e7-8959-f87044a9d516.png)
![image](https://user-images.githubusercontent.com/326242/31424218-b051792e-ae1e-11e7-9abe-21a35717ca31.png)

**Comment by ben7th** [comment]
@fushang318 我看看

**Comment by ben7th** [comment]
@fushang318 不是 git 是 gif

**Comment by ben7th** [comment]
@fushang318 脚本里图片网址也写错了，https:// 写了两遍

**Comment by fushang318** [comment]
@ben7th 
改好了
